#此启动程序工作流适用于在多个平台上运行的CMake项目.如果只需要单个平台，则有不同的启动程序工作流。
#请参阅： https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
名称：CMake在多个平台上

在……之上：
推：
分支机构：[“主”]["主"]
pull_request：
分支机构：[“主”]["主"]

作业：
建立：
运行时间：${{matrix.os}}{{matrix.os}}

策略：
#将fail-fast设置为false以确保所有矩阵组合的反馈都已传递.当您的工作流稳定时，请考虑将此设置更改为true.
fail-fast:false

#设置矩阵运行以下3种配置：
#1.<Windows、Release、默认运行程序映像、默认生成器上的最新MSVC编译器工具链>
#2.<Linux、Release、默认运行器映像、默认生成器上的最新GCC编译器工具链>
#3.<Linux，发行版，最新的Clang编译器工具链，默认跑步者映像，默认生成器>
      #
#要添加更多生成类型(发布、调试、RelWithDebInfo等)，请自定义build_type列表。
矩阵：
操作系统：[Ubuntu-最新，Windows-最新][Ubuntu-最新，Windows-最新]
组建类型(_T)：[发布][发布]
C编译器：[GCC，哐啷，CL](_C)[GCC，哐啷，CL](_C)
包括：
-os：窗口-最新
C编译器(_C)：cl
CPP编译器(_C)：cl
-os:ubuntu-latest
编译器：GCC(_C)
CPP编译器(_C)：g++
-os:ubuntu-latest
C编译器(_C): 叮当声
CPP_compiler: CPP_compiler:叮当声++
排除:
          - 操作系统: -os:Windows-最新
C编译器(_C): 编译器：GCC(_C)
          - 操作系统: -os:Windows-最新
C编译器(_C): 编译器：叮当(_C)
          - 操作系统: -os:Ubuntu-最新
C编译器(_C): C编译器(_C)：cl

步骤:
    - uses: -使用：操作/结帐@v4

    - 姓名: -名称：设置可重用字符串
#将重复的输入字符串(如生成输出目录)转换为步骤输出。 这些步骤输出可在整个工作流文件中使用。 #将重复的输入字符串(如生成输出目录)转换为步骤输出。 这些步骤输出可在整个工作流文件中使用。
身份标识: 身份标识：字符串
壳: 壳:猛击
跑: |
回声""build-output-dir=${{github.workspace}}/build">>"$GITHUB_OUTPUT"

    - 姓名: -名称：配置CMake
#在'建立'子目录中配置CMake.只有在使用单一组态产生器(例如make)时，才需要'CMMAKE_BUILD_TYPE'.#在'建立'子目录中设定CMake.只有在使用单一组态产生器(例如make)时，才需要'CMake_BUILD_TYPE'。
#请参阅https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type#请参阅https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
跑: >
CMake-B${{steps.strings.outputs.build-output-dir}}
-DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}
-DCMAKE_C_COMPILER=${{matrix.c_compiler}}
-DCMAKE_BUILD_TYPE=${{matrix.build_type}}
-s${{github.workspace}}

    - 姓名: -名称：内部版本
#使用给定的配置生成程序。请注意，需要--配置，因为默认的Windows生成器是多配置生成器(Visual Studio生成器)。#使用给定的配置生成程序。请注意，需要--配置，因为默认的Windows生成器是多配置生成器(Visual Studio生成器)。
跑: 运行：cmake--生成${{steps.strings.outputs.build-output-dir}}--config${{matrix.build_type}}{{steps.strings.outputs.build-output-dir}}--config${{matrix.build_type}}

    - 姓名: -名称：试验
工作目录: 工作目录：${{steps.strings.outputs.build-output-dir}}{{steps.strings.outputs.build-output-dir}}
#执行CMake配置定义的测试.请注意，之所以需要--构建配置，是因为默认的Windows生成器是一个多配置生成器(VisualStudio生成器)。#执行CMake配置定义的测试.请注意，之所以需要--构建配置，是因为默认的Windows生成器是一个多配置生成器(VisualStudio生成器)。
#有关更多详细信息，请参见https://cmake.org/cmake/help/latest/manual/ctest.1.html#更多详情请参见https://cmake.org/cmake/help/latest/manual/ctest.1.html
跑: 运行：ctest-build-config${{matrix.build_type}}{{matrix.build_type}}
